export const CustomerData = [
  {
    id: "1",
    Code: "CU001",
    image:"user-33.png",
    Customer: "Carl Evans",
    Email: "carlevans@example.com",
    Phone: "+12163547758",
    Country: "Germany",
    status: "Active",
  },
  {
    id: "2",
    Code: "CU002",
    image:"user-02.png",
    Customer: "Minerva Rameriz",
    Email: "rameriz@example.com",
    Phone: "+11367529510",
    Country: "Japan",
    status: "Active",
  },
  {
    id: "3",
    Code: "CU003",
    image:"user-34.png",
    Customer: "Robert Lamon",
    Email: "robert@example.com",
    Phone: "+15362789414",
    Country: "USA",
    status: "Active",
  },
  {
    id: "4",
    Code: "CU004",
    image:"user-35.png",
    Customer: "Patricia Lewis",
    Email: "patricia@example.com",
    Phone: "+18513094627",
    Country: "Austria",
    status: "Active",
  },
  {
    id: "5",
    Code: "CU005",
    image:"user-36.png",
    Customer: "Mark Joslyn",
    Email: "markjoslyn@example.com",
    Phone: "+14678219025",
    Country: "Turkey",
    status: "Active",
  },
  {
    id: "6",
    Code: "CU006",
    image:"user-37.png",
    Customer: "Marsha Betts",
    Email: "marshabetts@example.com",
    Phone: "+10913278319",
    Country: "Mexico",
    status: "Active",
  },
  {
    id: "7",
    Code: "CU007",
    image:"user-28.png",
    Customer: "Daniel Jude",
    Email: "daieljude@example.com",
    Phone: "+19125852947",
    Country: "France",
    status: "Active",
  },
  {
    id: "8",
    Code: "CU008",
    image:"user-38.png",
    Customer: "Emma Bates",
    Email: "emmabates@example.com",
    Phone: "+13671835209",
    Country: "Greece",
    status: "Active",
  },
  {
    id: "9",
    Code: "CU009",
    image:"user-39.png",
    Customer: "Richard Fralick",
    Email: "richard@example.com",
    Phone: "+19756194733",
    Country: "Italy",
    status: "Active",
  },
  {
    id: "10",
    Code: "CU010",
    image:"user-40.png",
    Customer: "Michelle Robison",
    Email: "robinson@example.com",
    Phone: "+19167850925",
    Country: "China",
    status: "Active",
  },
];
